# Generated by Django 3.2 on 2021-06-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(null=True)),
                ('address_prefecture', models.CharField(max_length=10)),
                ('address_city', models.CharField(max_length=20)),
                ('hear_from', models.CharField(max_length=30)),
                ('introduced', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_email1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('continuous_visit_count', models.IntegerField(default=0, null=True)),
                ('first_visit', models.DateTimeField(null=True)),
                ('previous_visit', models.DateTimeField(null=True)),
                ('last_visit', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_email2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
